# Generated by Django 5.2.1 on 2025-05-22 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60)),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time_create')),
                ('time_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Time_update')),
                ('is_published', models.BooleanField(default=True, verbose_name='Status')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=300, verbose_name='Ad')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Yaranma tarixi')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Ad')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Yaranma tarixi')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Ad')),
                ('surname', models.CharField(max_length=300, verbose_name='Soyad')),
                ('age', models.PositiveIntegerField(verbose_name='Yaş')),
                ('birthday', models.DateField(verbose_name='Doğum tarixi')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Yaranma tarixi')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.gender', verbose_name='Cinsi')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Ad')),
                ('price', models.FloatField(verbose_name='Qiymət')),
                ('tax_price', models.FloatField(blank=True, null=True, verbose_name='Tax qiymət')),
                ('discount_price', models.FloatField(blank=True, null=True, verbose_name='Endirimli qiymət')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Yaranma tarixi')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('category', models.CharField(choices=[('chair', 'Chair'), ('beds', 'Beds'), ('sofa', 'Sofa'), ('lamp', 'Lamp')], default='chair', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='news.author')),
                ('tags', models.ManyToManyField(blank=True, to='news.tag', verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d/', verbose_name='Image')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time_create')),
                ('time_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Time_update')),
                ('is_published', models.BooleanField(default=True, null=True, verbose_name='Status')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.author', verbose_name='Author')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='newss', to='news.category')),
                ('tags', models.ManyToManyField(blank=True, to='news.tag', verbose_name='Tags')),
            ],
        ),
    ]
