# Generated by Django 5.2.1 on 2025-05-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_about_us_contactmessage_testimonial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_price',
        ),
    ]
