# Generated by Django 5.2.1 on 2025-05-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_product_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
