# Generated by Django 5.2.1 on 2025-05-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='investments/')),
                ('security_type', models.CharField(max_length=100)),
                ('investment_multiple', models.CharField(max_length=50)),
                ('maturity', models.CharField(max_length=50)),
                ('min_investment', models.CharField(max_length=50)),
                ('raised_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
